
package com.creditsafe.ws;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataInputService", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataInputService {


    /**
     * 
     * @param orderNumber
     * @param report
     * @param additionalRetrievalData
     * @param onlineRetrievalCriteria
     * @return
     *     returns com.creditsafe.ws.SimpleResult
     */
    @WebMethod(operationName = "DeliverOfflineCompanyReport", action = "http://www.creditsafe.com/globaldata/operations/administration/DataInputService/DeliverOfflineCompanyReport")
    @WebResult(name = "DeliverOfflineCompanyReportResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
    @RequestWrapper(localName = "DeliverOfflineCompanyReport", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.DeliverOfflineCompanyReport")
    @ResponseWrapper(localName = "DeliverOfflineCompanyReportResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.DeliverOfflineCompanyReportResponse")
    public SimpleResult deliverOfflineCompanyReport(
        @WebParam(name = "orderNumber", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        BigInteger orderNumber,
        @WebParam(name = "report", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        String report,
        @WebParam(name = "onlineRetrievalCriteria", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        SearchCriteria onlineRetrievalCriteria,
        @WebParam(name = "additionalRetrievalData", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        CustomData additionalRetrievalData);

    /**
     * 
     * @param orderNumber
     * @param reasonCode
     * @param additionalData
     * @return
     *     returns com.creditsafe.ws.SimpleResult
     */
    @WebMethod(operationName = "MarkFailedOfflineOrder", action = "http://www.creditsafe.com/globaldata/operations/administration/DataInputService/MarkFailedOfflineOrder")
    @WebResult(name = "MarkFailedOfflineOrderResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
    @RequestWrapper(localName = "MarkFailedOfflineOrder", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.MarkFailedOfflineOrder")
    @ResponseWrapper(localName = "MarkFailedOfflineOrderResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.MarkFailedOfflineOrderResponse")
    public SimpleResult markFailedOfflineOrder(
        @WebParam(name = "orderNumber", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        BigInteger orderNumber,
        @WebParam(name = "reasonCode", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Long reasonCode,
        @WebParam(name = "additionalData", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        CustomData additionalData);

    /**
     * 
     * @param orderNumber
     * @param firstRow
     * @param countryCode
     * @param rowCount
     * @return
     *     returns com.creditsafe.ws.OfflineReportOrdersList
     */
    @WebMethod(operationName = "ListOfflineOrders", action = "http://www.creditsafe.com/globaldata/operations/administration/DataInputService/ListOfflineOrders")
    @WebResult(name = "ListOfflineOrdersResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
    @RequestWrapper(localName = "ListOfflineOrders", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.ListOfflineOrders")
    @ResponseWrapper(localName = "ListOfflineOrdersResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.ListOfflineOrdersResponse")
    public OfflineReportOrdersList listOfflineOrders(
        @WebParam(name = "orderNumber", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        BigInteger orderNumber,
        @WebParam(name = "countryCode", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        CountryCode countryCode,
        @WebParam(name = "firstRow", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Long firstRow,
        @WebParam(name = "rowCount", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Long rowCount);

    /**
     * 
     * @param orderNumber
     * @param firstRow
     * @param olderThan
     * @param newerThan
     * @param countryCode
     * @param successfulDelivery
     * @param rowCount
     * @param userId
     * @return
     *     returns com.creditsafe.ws.ReportSnapshotsList
     */
    @WebMethod(operationName = "ListRealisedOrders", action = "http://www.creditsafe.com/globaldata/operations/administration/DataInputService/ListRealisedOrders")
    @WebResult(name = "ListRealisedOrdersResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
    @RequestWrapper(localName = "ListRealisedOrders", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.ListRealisedOrders")
    @ResponseWrapper(localName = "ListRealisedOrdersResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.ListRealisedOrdersResponse")
    public ReportSnapshotsList listRealisedOrders(
        @WebParam(name = "orderNumber", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        BigInteger orderNumber,
        @WebParam(name = "countryCode", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        CountryCode countryCode,
        @WebParam(name = "userId", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Long userId,
        @WebParam(name = "newerThan", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        XMLGregorianCalendar newerThan,
        @WebParam(name = "olderThan", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        XMLGregorianCalendar olderThan,
        @WebParam(name = "successfulDelivery", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Boolean successfulDelivery,
        @WebParam(name = "firstRow", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Long firstRow,
        @WebParam(name = "rowCount", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Long rowCount);

    /**
     * 
     * @param orderNumber
     * @return
     *     returns com.creditsafe.ws.ReportSnapshot
     */
    @WebMethod(operationName = "GetStoredReport", action = "http://www.creditsafe.com/globaldata/operations/administration/DataInputService/GetStoredReport")
    @WebResult(name = "GetStoredReportResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
    @RequestWrapper(localName = "GetStoredReport", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.GetStoredReport")
    @ResponseWrapper(localName = "GetStoredReportResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.GetStoredReportResponse")
    public ReportSnapshot getStoredReport(
        @WebParam(name = "orderNumber", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        BigInteger orderNumber);

    /**
     * 
     * @param orderNumber
     * @param report
     * @param additionalRetrievalData
     * @param updateAllInstances
     * @param onlineRetrievalCriteria
     * @return
     *     returns com.creditsafe.ws.SimpleResult
     */
    @WebMethod(operationName = "UpdateStoredReport", action = "http://www.creditsafe.com/globaldata/operations/administration/DataInputService/UpdateStoredReport")
    @WebResult(name = "UpdateStoredReportResult", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
    @RequestWrapper(localName = "UpdateStoredReport", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.UpdateStoredReport")
    @ResponseWrapper(localName = "UpdateStoredReportResponse", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration", className = "com.creditsafe.ws.UpdateStoredReportResponse")
    public SimpleResult updateStoredReport(
        @WebParam(name = "orderNumber", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        BigInteger orderNumber,
        @WebParam(name = "report", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        String report,
        @WebParam(name = "onlineRetrievalCriteria", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        SearchCriteria onlineRetrievalCriteria,
        @WebParam(name = "additionalRetrievalData", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        CustomData additionalRetrievalData,
        @WebParam(name = "updateAllInstances", targetNamespace = "http://www.creditsafe.com/globaldata/operations/administration")
        Boolean updateAllInstances);

}
